version: '3.11'

services:
  db:
    image: postgres:default
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing123
      POSTGRES_DB: blog
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
